name = "Bibliography"
uuid = "f1be7e48-bf82-45af-a471-ae754a193061"
authors = ["azzaare <jf@baffier.fr>"]
version = "0.2.1"

[deps]
BibInternal = "2027ae74-3657-4b95-ae00-e2f7d55c3e64"
BibParser = "13533e5b-e1c2-4e57-8cef-cac5e52f6474"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
BibInternal = "^0.2.1"
BibParser = "^0.1.4"
DataStructures = "^0.17.19"
julia = "^1.4"
