name = "Bibliography"
uuid = "f1be7e48-bf82-45af-a471-ae754a193061"
authors = ["azzaare <jf@baffier.fr>"]
version = "0.2.19"

[deps]
BibInternal = "2027ae74-3657-4b95-ae00-e2f7d55c3e64"
BibParser = "13533e5b-e1c2-4e57-8cef-cac5e52f6474"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
BibInternal = "0.3.3"
BibParser = "0.2.1"
DataStructures = "0.18"
FileIO = "1"
YAML = "0.4"
julia = "1.6"
