[deps]
BibInternal = "2027ae74-3657-4b95-ae00-e2f7d55c3e64"
BibParser = "13533e5b-e1c2-4e57-8cef-cac5e52f6474"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
BibInternal = "^0.2.2"
BibParser = "^0.1.7"
Documenter = "^0.25"
